# 3. Reshaping, Transposing and Concatenating Arrays

In [18]:
import numpy as np

NumPy arrays can be reshaped. When reshaping an array, the content stays the same, making it a very fast operation.

For example, if we have a 2D array (matrix) `arr` of shape 3x3 and we want to "flatten" it to a 1-dimensional array of length $9$, we can simply write `arr.reshape(9)`. We can also use `-1` to let NumPy infer the size in a dimension when possible. We can also reshape the flat array back into a 2-dimensional one.

In [19]:
# Create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(f"shape: {arr.shape}")

# Flatten the array
arr = arr.reshape(9) # or arr.reshape(-1)
print(arr)
print(f"shape: {arr.shape}")

# Reshape it back to a 3x3 array
arr = arr.reshape(-1, 3) # or arr.reshape(3, 3) or arr.reshape(3, -1)
print(arr)
print(f"shape: {arr.shape}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
[1 2 3 4 5 6 7 8 9]
shape: (9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)


Here are some more examples of reshaping.

In [20]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(f"shape: {arr.shape}")

arr = arr.reshape(-1, 4)
print(arr)
print(f"shape: {arr.shape}")

arr = arr.reshape(1, 8)
print(arr)
print(f"shape: {arr.shape}")

arr = arr.reshape(8, 1)
print(arr)
print(f"shape: {arr.shape}")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
[[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
[[1 2 3 4 5 6 7 8]]
shape: (1, 8)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
shape: (8, 1)


We can also transpose a matrix `arr` by using `arr.transpose()` or simply `arr.T`. For "transposing" higher-dimensional arrays, see `np.swapaxes()` ([documentation](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html)).

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

arr_transposed = arr.T # or arr.transpose()
print(arr_transposed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


NumPy offers many functions to join multiple NumPy arrays together.

The two main ones are `np.concatenate()` ([documentation](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)) and `np.stack()` ([documentation](https://numpy.org/doc/stable/reference/generated/numpy.stack.html)).

The function `np.stack()` stacks arrays along a new dimension, whereas `np.concatenate()` concatenate arrays along an existing axis without adding a new dimension.

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(f"arr1 = {arr1}")
print(f"arr2 = {arr2}")

# Stack arrays along a new axis (in dimension 0, i.e., stack as rows)
stacked_arr = np.stack((arr1, arr2), axis=0)
print("Stacked in new dimension 0")
print(stacked_arr)
print(f"shape: {stacked_arr.shape}")

# Stack arrays along another new axis
stacked_arr = np.stack((arr1, arr2), axis=1)
print("Stacked in new dimension 1")
print(stacked_arr)
print(f"shape: {stacked_arr.shape}")

# Concatenate in existing dimension 0
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated in existing dimension")
print(concatenated_arr)
print(f"shape: {concatenated_arr.shape}")

arr1 = [1 2 3]
arr2 = [4 5 6]
Stacked in new dimension 0
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
Stacked in new dimension 1
[[1 4]
 [2 5]
 [3 6]]
shape: (3, 2)
Concatenated in existing dimension
[1 2 3 4 5 6]
shape: (6,)


Let us see how we can concatenate two 2-dimensional arrays as well.

In [23]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])

print("Original arrays")
print(f"arr3 =\n{arr3} (shape: {arr3.shape})\n")
print(f"arr4 =\n{arr4} (shape: {arr4.shape})\n")

# Concatenate arrays along axis=0
concatenated_arr = np.concatenate((arr3, arr4), axis=0)
print("Stacked along dimension 0 (rows)")
print(concatenated_arr)
print(f"new shape: {concatenated_arr.shape}")

# Concatenate arrays along axis=1
concatenated_arr = np.concatenate((arr3, arr4), axis=1)
print("Stacked along dimension 1 (columns)")
print(concatenated_arr)
print(f"new shape: {concatenated_arr.shape}")

Original arrays
arr3 =
[[1 2 3]
 [4 5 6]] (shape: (2, 3))

arr4 =
[[ 7  8  9]
 [10 11 12]] (shape: (2, 3))

Stacked along dimension 0 (rows)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
new shape: (4, 3)
Stacked along dimension 1 (columns)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
new shape: (2, 6)


Here is a full list (I think) of different functions for stacking and concatenating arrays in NumPy. But usually, `concatenate` and `stack` will be sufficient for most tasks.

**Concatenation Functions:**
- `np.concatenate()`
- `np.vstack()`
- `np.hstack()`
- `np.dstack()`
- `np.column_stack()`
- `np.row_stack()`

**Stacking Functions:**
- `np.stack()`
- `np.block()`
- `np.tile()`
- `np.repeat()`

**Shorthand Utilities:**
- `np.c_[]`
- `np.r_[]`

## Exercises

### 1. Matrix from `np.arange()`

Create a NumPy array `arr` storing the matrix $\begin{pmatrix}1&4&7\\10&13&16\\19&22&25\end{pmatrix}$ using only `np.arange()` and `arr.reshape()`. Print the array to verify your solution.

In [24]:
# You code here
arr = ...

# Solution:
arr = np.arange(1, 26, 3).reshape(-1 ,3)
print(arr)

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


### 2. 2D to 3D

Reshape the 2D array `arr` of shape `(2, 9)` into a 3D array of shape `(2, 3, 3)`. Print the array before and after reshaping to better understand what is going on.

In [25]:
arr = np.array([[3, 6, 1, 9, 2, 4, 8, 3, 2], [0, 1, 6, 3, 7, 4, 3, 6, 1]])

# Your code here
...

# Solution
print(arr)
arr = arr.reshape(2, 3, 3)
print(arr)

[[3 6 1 9 2 4 8 3 2]
 [0 1 6 3 7 4 3 6 1]]
[[[3 6 1]
  [9 2 4]
  [8 3 2]]

 [[0 1 6]
  [3 7 4]
  [3 6 1]]]


### 3. Stacking Grades

You are given three 1D arrays representing the scores of students in Math, Science, and English, respectively.

1. Use `np.stack()` to combine the arrays along a new axis so that each row in the resulting array represents the scores of a single.
2. Print the resulting array and its shape. 

The output should be as follows:

```python
[[85 88 87]
 [90 94 85]
 [78 80 90]
 [92 86 88]]
Shape: (4, 3)
```

In [26]:
math_scores = np.array([85, 90, 78, 92])
science_scores = np.array([88, 94, 80, 86])
english_scores = np.array([87, 85, 90, 88])

# Your code here
stacked_scores = ...

# Solution
stacked_scores = np.stack((math_scores, science_scores, english_scores), axis=1)
# Print the resulting array
print("Stacked Scores:")
print(stacked_scores)
# Verify the shape
print("Shape:", stacked_scores.shape)

Stacked Scores:
[[85 88 87]
 [90 94 85]
 [78 80 90]
 [92 86 88]]
Shape: (4, 3)


### 4. °Concatenate

You are given two arrays `temperatures_part1` and `temperatures_part2`, both of shape `(7, 2)`.

The two arrays contains the morning temperature (first column) and evening temperature (second column) for a period of 7 days.

1. Use `np.concatenate()` to combine the arrays along the vertical axis (axis 0).
2. Print the resulting array.
3. Verify the shape of the resulting array to ensure it has the correct dimensions `(14, 2)`.

In [27]:
temperatures_part1 = np.array([[15, 22], 
                               [16, 23], 
                               [15, 21], 
                               [14, 20], 
                               [13, 19], 
                               [12, 18], 
                               [14, 21]])

temperatures_part2 = np.array([[18, 25], 
                               [17, 24], 
                               [19, 26], 
                               [16, 23], 
                               [15, 22], 
                               [14, 21], 
                               [17, 24]])

# Your code here
concatenated_temperatures = ...

# Solution
concatenated_temperatures = np.concatenate((temperatures_part1, temperatures_part2), axis=0)
# Print the resulting array
print("Concatenated Temperatures:")
print(concatenated_temperatures)
# Verify the shape
print("Shape:", concatenated_temperatures.shape)

Concatenated Temperatures:
[[15 22]
 [16 23]
 [15 21]
 [14 20]
 [13 19]
 [12 18]
 [14 21]
 [18 25]
 [17 24]
 [19 26]
 [16 23]
 [15 22]
 [14 21]
 [17 24]]
Shape: (14, 2)
